# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyUSB0
baud: 57600
timeout: 0.1

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.097
wheel_track: 0.4060
encoder_resolution: 13 #  from Pololu for 131:1 motors
gear_reduction: 30
motors_reversed: False
#linear_scale_correction:0.998
#angular_scale_correction:0.9872
# === PID parameters
AKp: 10
AKd: 12
AKi: 0
AKo: 50

BKp: 10
BKd: 12
BKi: 0
BKo: 50

CKp: 10
CKd: 12
CKi: 0
CKo: 50

DKp: 10
DKd: 12
DKi: 0
DKo: 50
#accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  dht_22:               {pin: 0xA0, type: DHT22, rate: 0.2},
  arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
